# Generated by Django 3.2.7 on 2022-10-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='名称')),
                ('category', models.CharField(blank=True, choices=[('normal', '日常'), ('furniture', '家具'), ('kitchen', '厨房'), ('bathroom', '卫浴'), ('digital', '数码')], db_index=True, default='normal', max_length=50, verbose_name='类型')),
            ],
        ),
    ]
